#!/bin/bash
clear
echo "Make sure you are in proper directory/folder."
echo ""
echo "Do not close this terminal"
echo ""
echo "Enter your Project name"
echo ""
read name
echo ""
echo "creating files for you... Please wait.."
npx create-react-app $name > /dev/null
echo ""
echo "Your project is created"
cd $name
rm -rf .git
clear
echo '''
inpu (){

echo "To run this tool later type < sh tool > and make sure your terminal path is your project folder"
echo ""
echo "select option"
echo "  1) Test"
echo "  2) Run"
echo "  3) Build"
echo "  4) Eject"

read n
case $n in
  1) npm test;;
  2) npm start;;
  3) npm run build;;
  4) npm run eject;;
  *) echo "invalid option";;
esac
}
inpu
''' > tool
sh tool