export const GET_WOMENS_DATA_REQUEST = 'GET_WOMENS_DATA_REQUEST';
export const GET_WOMENS_DATA_SUCCESS = 'GET_WOMENS_DATA_SUCCESS';
export const GET_WOMENS_DATA_FAILURE = 'GET_WOMENS_DATA_FAILURE';

export const GET_MENS_DATA_REQUEST = 'GET_MENS_DATA_REQUEST';
export const GET_MENS_DATA_SUCCESS = 'GET_MENS_DATA_SUCCESS';
export const GET_MENS_DATA_FAILURE = 'GET_MENS_DATA_FAILURE';