export const GET_HOME_SLIDESHOW_REQUEST = 'GET_HOME_SLIDESHOW_REQUEST';
export const GET_HOME_SLIDESHOW_SUCCESS = 'GET_HOME_SLIDESHOW_SUCCESS';
export const GET_HOME_SLIDESHOW_FAILURE = 'GET_HOME_SLIDESHOW_FAILURE';

export const GET_HOME_MAINBODY_REQUEST = 'GET_HOME_MAINBODY_REQUEST';
export const GET_HOME_MAINBODY_SUCCESS = 'GET_HOME_MAINBODY_SUCCESS';
export const GET_HOME_MAINBODY_FAILURE = 'GET_HOME_MAINBODY_FAILURE';

export const GET_HOME_MAINBODY1_REQUEST = 'GET_HOME_MAINBODY1_REQUEST';
export const GET_HOME_MAINBODY1_SUCCESS = 'GET_HOME_MAINBODY1_SUCCESS';
export const GET_HOME_MAINBODY1_FAILURE = 'GET_HOME_MAINBODY1_FAILURE';

export const GET_BREAKOUT_BRANDS_REQUEST = 'GET_BREAKOUT_BRANDS_REQUEST';
export const GET_BREAKOUT_BRANDS_SUCCESS = 'GET_BREAKOUT_BRANDS_SUCCESS';
export const GET_BREAKOUT_BRANDS_FAILURE = 'GET_BREAKOUT_BRANDS_FAILURE';

export const GET_TRENDING_NOW_REQUEST = 'GET_TRENDING_NOW_REQUEST';
export const GET_TRENDING_NOW_SUCCESS = 'GET_TRENDING_NOW_SUCCESS';
export const GET_TRENDING_NOW_FAILURE = 'GET_TRENDING_NOW_FAILURE';

export const GET_HOTNOW_REQUEST = 'GET_HOTNOW_REQUEST';
export const GET_HOTNOW_SUCCESS = 'GET_HOTNOW_SUCCESS';
export const GET_HOTNOW_FAILURE = 'GET_HOTNOW_FAILURE';

export const GET_WOMENS_ALL_DATA_REQUEST = 'GET_WOMENS_ALL_DATA_REQUEST';
export const GET_WOMENS_ALL_DATA_SUCCESS = 'GET_WOMENS_ALL_DATA_SUCCESS';
export const GET_WOMENS_ALL_DATA_FAILURE = 'GET_WOMENS_ALL_DATA_FAILURE';

export const GET_WOMENS_COATS_REQUEST = 'GET_WOMENS_COATS_REQUEST';
export const GET_WOMENS_COATS_SUCCESS = 'GET_WOMENS_COATS_SUCCESS';
export const GET_WOMENS_COATS_FAILURE = 'GET_WOMENS_COATS_FAILURE';

export const GET_MENS_DATA_REQUEST = 'GET_MENS_DATA_REQUEST';
export const GET_MENS_DATA_SUCCESS = 'GET_MENS_DATA_SUCCESS';
export const GET_MENS_DATA_FAILURE = 'GET_MENS_DATA_FAILURE';